import { ProposalStatus } from "../../types/Struct";

export const movieProposals = [
	{
		id: 1,
		title: "The Last Guardian",
		status: ProposalStatus.Pending,
		votesFor: 10,
		votesAgainst: 2,
		proposer: "Ava Green",
		executionTime: 1722508800,
		votingStartTime: 1722100800,
		votingEndTime: 1722259200,
		totalVotes: 12,
		description: "A fantasy adventure where a young girl discovers she is the last of a line of guardians tasked with protecting a mystical realm.",
	},
	{
		id: 2,
		title: "Cyber Dawn",
		status: ProposalStatus.Added,
		votesFor: 15,
		votesAgainst: 3,
		proposer: "Liam Brown",
		executionTime: 1723411200,
		votingStartTime: 1723017600,
		votingEndTime: 1723171200,
		totalVotes: 18,
		description: "In a dystopian future, a hacker teams up with a rogue AI to take down a corrupt corporation controlling society.",
	},
	{
		id: 3,
		title: "The Silent Witness",
		status: ProposalStatus.Active,
		votesFor: 20,
		votesAgainst: 8,
		proposer: "Olivia Smith",
		executionTime: 1724505600,
		votingStartTime: 1724102400,
		votingEndTime: 1724256000,
		totalVotes: 28,
		description: "A gripping thriller where a mute girl becomes the key witness to a crime and must find a way to communicate what she saw.",
	},
	{
		id: 4,
		title: "Love Through Time",
		status: ProposalStatus.Passed,
		votesFor: 25,
		votesAgainst: 5,
		proposer: "Noah Johnson",
		executionTime: 1725724800,
		votingStartTime: 1725321600,
		votingEndTime: 1725475200,
		totalVotes: 30,
		description: "A romantic drama where two souls are connected across different timelines, fighting to reunite.",
	},
	{
		id: 5,
		title: "Alien Encounter",
		status: ProposalStatus.Failed,
		votesFor: 5,
		votesAgainst: 15,
		proposer: "Emma Davis",
		executionTime: 1726358400,
		votingStartTime: 1725955200,
		votingEndTime: 1726108800,
		totalVotes: 20,
		description: "A sci-fi adventure where a group of friends must survive an alien invasion while uncovering the truth behind their motives.",
	},
	{
		id: 6,
		title: "The Cursed Symphony",
		status: ProposalStatus.Canceled,
		votesFor: 12,
		votesAgainst: 8,
		proposer: "Jacob Wilson",
		executionTime: 1727059200,
		votingStartTime: 1726665600,
		votingEndTime: 1726819200,
		totalVotes: 20,
		description: "A horror film about a composer who discovers an ancient melody that brings forth dark forces.",
	},
	{
		id: 7,
		title: "Shattered Dreams",
		status: ProposalStatus.Pending,
		votesFor: 18,
		votesAgainst: 7,
		proposer: "Sophia Martinez",
		executionTime: 1727702400,
		votingStartTime: 1727308800,
		votingEndTime: 1727462400,
		totalVotes: 25,
		description: "A drama following a young athlete's journey as she overcomes adversity to achieve her dreams.",
	},
	{
		id: 8,
		title: "Into the Abyss",
		status: ProposalStatus.Active,
		votesFor: 30,
		votesAgainst: 2,
		proposer: "William Anderson",
		executionTime: 1728902400,
		votingStartTime: 1728508800,
		votingEndTime: 1728662400,
		totalVotes: 32,
		description: "A survival thriller about a group of divers who uncover an underwater mystery that could change history.",
	},
	{
		id: 9,
		title: "The Enchanted Forest",
		status: ProposalStatus.Added,
		votesFor: 22,
		votesAgainst: 4,
		proposer: "Mia Thomas",
		executionTime: 1729507200,
		votingStartTime: 1729104000,
		votingEndTime: 1729257600,
		totalVotes: 26,
		description: "A family-friendly fantasy where children embark on an adventure in a magical forest filled with talking animals and hidden treasures.",
	},
	{
		id: 10,
		title: "Parallel Lives",
		status: ProposalStatus.Passed,
		votesFor: 28,
		votesAgainst: 6,
		proposer: "James Jackson",
		executionTime: 1730102400,
		votingStartTime: 1729708800,
		votingEndTime: 1729862400,
		totalVotes: 34,
		description: "A thought-provoking drama about two people living parallel lives that intersect in unexpected ways.",
	},
	{
		id: 11,
		title: "The Art of Deception",
		status: ProposalStatus.Failed,
		votesFor: 10,
		votesAgainst: 20,
		proposer: "Isabella White",
		executionTime: 1730908800,
		votingStartTime: 1730505600,
		votingEndTime: 1730659200,
		totalVotes: 30,
		description: "A heist movie where a team of thieves must outsmart a master forger to steal a priceless painting.",
	},
	{
		id: 12,
		title: "Haunted Hearts",
		status: ProposalStatus.Canceled,
		votesFor: 14,
		votesAgainst: 6,
		proposer: "Ethan Hall",
		executionTime: 1731600000,
		votingStartTime: 1731196800,
		votingEndTime: 1731350400,
		totalVotes: 20,
		description: "A romantic horror where two lovers are haunted by the ghosts of their past.",
	},
	{
		id: 13,
		title: "Rising Phoenix",
		status: ProposalStatus.Pending,
		votesFor: 35,
		votesAgainst: 10,
		proposer: "Grace Lee",
		executionTime: 1732204800,
		votingStartTime: 1731801600,
		votingEndTime: 1731955200,
		totalVotes: 45,
		description: "A biographical film about a renowned activist's fight for social justice and equality.",
	},
	{
		id: 14,
		title: "The Whispering Shadows",
		status: ProposalStatus.Active,
		votesFor: 27,
		votesAgainst: 3,
		proposer: "Lucas Turner",
		executionTime: 1732809600,
		votingStartTime: 1732406400,
		votingEndTime: 1732560000,
		totalVotes: 30,
		description: "A psychological thriller where a detective investigates a series of murders linked to a mysterious figure from his past.",
	},
	{
		id: 15,
		title: "Winds of Change",
		status: ProposalStatus.Added,
		votesFor: 18,
		votesAgainst: 12,
		proposer: "Amelia Harris",
		executionTime: 1733414400,
		votingStartTime: 1733011200,
		votingEndTime: 1733164800,
		totalVotes: 30,
		description: "A drama about a young woman's struggle to rebuild her life after a devastating hurricane.",
	},
	{
		id: 16,
		title: "Beyond the Horizon",
		status: ProposalStatus.Passed,
		votesFor: 40,
		votesAgainst: 2,
		proposer: "Henry Walker",
		executionTime: 1734019200,
		votingStartTime: 1733616000,
		votingEndTime: 1733769600,
		totalVotes: 42,
		description: "A sci-fi epic about explorers who venture beyond the known universe to discover new worlds.",
	},
	{
		id: 17,
		title: "The Last Spell",
		status: ProposalStatus.Failed,
		votesFor: 8,
		votesAgainst: 22,
		proposer: "Ella Young",
		executionTime: 1734624000,
		votingStartTime: 1734220800,
		votingEndTime: 1734374400,
		totalVotes: 30,
		description: "A fantasy adventure where a young sorceress fights to save her kingdom from dark magic.",
	}]